# Generated by Django 2.1.1 on 2018-09-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='text0',
            name='oTextHeadline0',
            field=models.ManyToManyField(related_name='oTextHeadline0', to='api.Word'),
        ),
        migrations.AddField(
            model_name='text0',
            name='transHeadline0',
            field=models.ManyToManyField(related_name='transHeadline0', to='api.Word'),
        ),
    ]
